<?php
/**
 * NestedProjectStatusListItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * NestedProjectStatusListItem Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NestedProjectStatusListItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'NestedProjectStatusListItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'name' => 'string',
        'plans_project' => 'bool',
        'closes_project' => 'bool',
        'invoices_project' => 'bool',
        'closes_planning' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'name' => null,
        'plans_project' => null,
        'closes_project' => null,
        'invoices_project' => null,
        'closes_planning' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'plans_project' => 'plansProject',
        'closes_project' => 'closesProject',
        'invoices_project' => 'invoicesProject',
        'closes_planning' => 'closesPlanning'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'plans_project' => 'setPlansProject',
        'closes_project' => 'setClosesProject',
        'invoices_project' => 'setInvoicesProject',
        'closes_planning' => 'setClosesPlanning'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'plans_project' => 'getPlansProject',
        'closes_project' => 'getClosesProject',
        'invoices_project' => 'getInvoicesProject',
        'closes_planning' => 'getClosesPlanning'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['plans_project'] = isset($data['plans_project']) ? $data['plans_project'] : null;
        $this->container['closes_project'] = isset($data['closes_project']) ? $data['closes_project'] : null;
        $this->container['invoices_project'] = isset($data['invoices_project']) ? $data['invoices_project'] : null;
        $this->container['closes_planning'] = isset($data['closes_planning']) ? $data['closes_planning'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The ID of the status.
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the status.
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets plans_project
     *
     * @return bool
     */
    public function getPlansProject()
    {
        return $this->container['plans_project'];
    }

    /**
     * Sets plans_project
     *
     * @param bool $plans_project Whether this status denotes a planned-state of the project.
     *
     * @return $this
     */
    public function setPlansProject($plans_project)
    {
        $this->container['plans_project'] = $plans_project;

        return $this;
    }

    /**
     * Gets closes_project
     *
     * @return bool
     */
    public function getClosesProject()
    {
        return $this->container['closes_project'];
    }

    /**
     * Sets closes_project
     *
     * @param bool $closes_project Whether this status denotes a closed-state of the project.
     *
     * @return $this
     */
    public function setClosesProject($closes_project)
    {
        $this->container['closes_project'] = $closes_project;

        return $this;
    }

    /**
     * Gets invoices_project
     *
     * @return bool
     */
    public function getInvoicesProject()
    {
        return $this->container['invoices_project'];
    }

    /**
     * Sets invoices_project
     *
     * @param bool $invoices_project Whether this status denotes an invoiced-state of the project.
     *
     * @return $this
     */
    public function setInvoicesProject($invoices_project)
    {
        $this->container['invoices_project'] = $invoices_project;

        return $this;
    }

    /**
     * Gets closes_planning
     *
     * @return bool
     */
    public function getClosesPlanning()
    {
        return $this->container['closes_planning'];
    }

    /**
     * Sets closes_planning
     *
     * @param bool $closes_planning Whether the project planning is closed.
     *
     * @return $this
     */
    public function setClosesPlanning($closes_planning)
    {
        $this->container['closes_planning'] = $closes_planning;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


