<?php
/**
 * CondensedDivisionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CondensedDivisionTest Class Doc Comment
 *
 * @category    Class
 * @description CondensedDivision
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CondensedDivisionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CondensedDivision"
     */
    public function testCondensedDivision()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "exact_division_id"
     */
    public function testPropertyExactDivisionId()
    {
    }

    /**
     * Test attribute "gl_account_code"
     */
    public function testPropertyGlAccountCode()
    {
    }

    /**
     * Test attribute "gl_account_code_purchase"
     */
    public function testPropertyGlAccountCodePurchase()
    {
    }

    /**
     * Test attribute "journal_code"
     */
    public function testPropertyJournalCode()
    {
    }

    /**
     * Test attribute "journal_code_purchase"
     */
    public function testPropertyJournalCodePurchase()
    {
    }

    /**
     * Test attribute "sales_invoice_number_prefix"
     */
    public function testPropertySalesInvoiceNumberPrefix()
    {
    }
}
