<?php
/**
 * EquipmentBookingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EquipmentBookingTest Class Doc Comment
 *
 * @category    Class
 * @description EquipmentBooking
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EquipmentBookingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EquipmentBooking"
     */
    public function testEquipmentBooking()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "cost_price"
     */
    public function testPropertyCostPrice()
    {
    }

    /**
     * Test attribute "selling_price"
     */
    public function testPropertySellingPrice()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "log_date"
     */
    public function testPropertyLogDate()
    {
    }

    /**
     * Test attribute "project_security_link"
     */
    public function testPropertyProjectSecurityLink()
    {
    }

    /**
     * Test attribute "equipment_per_unit"
     */
    public function testPropertyEquipmentPerUnit()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "employees"
     */
    public function testPropertyEmployees()
    {
    }

    /**
     * Test attribute "equipment"
     */
    public function testPropertyEquipment()
    {
    }

    /**
     * Test attribute "equipment_group"
     */
    public function testPropertyEquipmentGroup()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "updated_by"
     */
    public function testPropertyUpdatedBy()
    {
    }
}
