<?php
/**
 * InvoiceDocumentLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceDocumentLineTest Class Doc Comment
 *
 * @category    Class
 * @description InvoiceDocumentLine
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceDocumentLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceDocumentLine"
     */
    public function testInvoiceDocumentLine()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {
    }

    /**
     * Test attribute "sort_index"
     */
    public function testPropertySortIndex()
    {
    }

    /**
     * Test attribute "linked_booking_items"
     */
    public function testPropertyLinkedBookingItems()
    {
    }

    /**
     * Test attribute "project_invoice_term_id"
     */
    public function testPropertyProjectInvoiceTermId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unit_name"
     */
    public function testPropertyUnitName()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "sub_total"
     */
    public function testPropertySubTotal()
    {
    }

    /**
     * Test attribute "surcharge_percentage"
     */
    public function testPropertySurchargePercentage()
    {
    }

    /**
     * Test attribute "vat_tariff_percentage"
     */
    public function testPropertyVatTariffPercentage()
    {
    }

    /**
     * Test attribute "vat_tariff_id"
     */
    public function testPropertyVatTariffId()
    {
    }

    /**
     * Test attribute "ledger"
     */
    public function testPropertyLedger()
    {
    }

    /**
     * Test attribute "cost_center"
     */
    public function testPropertyCostCenter()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "price_code"
     */
    public function testPropertyPriceCode()
    {
    }
}
