<?php
/**
 * MaterialPerUnitTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MaterialPerUnitTest Class Doc Comment
 *
 * @category    Class
 * @description MaterialPerUnit
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MaterialPerUnitTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MaterialPerUnit"
     */
    public function testMaterialPerUnit()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "selling_price"
     */
    public function testPropertySellingPrice()
    {
    }

    /**
     * Test attribute "article_number"
     */
    public function testPropertyArticleNumber()
    {
    }

    /**
     * Test attribute "ean_code"
     */
    public function testPropertyEanCode()
    {
    }

    /**
     * Test attribute "gl_account_code"
     */
    public function testPropertyGlAccountCode()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "material"
     */
    public function testPropertyMaterial()
    {
    }

    /**
     * Test attribute "material_unit"
     */
    public function testPropertyMaterialUnit()
    {
    }

    /**
     * Test attribute "supplier"
     */
    public function testPropertySupplier()
    {
    }

    /**
     * Test attribute "material_group"
     */
    public function testPropertyMaterialGroup()
    {
    }

    /**
     * Test attribute "delivery_time_in_days"
     */
    public function testPropertyDeliveryTimeInDays()
    {
    }

    /**
     * Test attribute "form_factor"
     */
    public function testPropertyFormFactor()
    {
    }

    /**
     * Test attribute "conversion_factor"
     */
    public function testPropertyConversionFactor()
    {
    }

    /**
     * Test attribute "vat_tariff"
     */
    public function testPropertyVatTariff()
    {
    }

    /**
     * Test attribute "visibility_flag"
     */
    public function testPropertyVisibilityFlag()
    {
    }

    /**
     * Test attribute "material_per_divisions"
     */
    public function testPropertyMaterialPerDivisions()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "updated_by"
     */
    public function testPropertyUpdatedBy()
    {
    }
}
