<?php
/**
 * MileageRegistrationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MileageRegistrationTest Class Doc Comment
 *
 * @category    Class
 * @description MileageRegistration
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MileageRegistrationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MileageRegistration"
     */
    public function testMileageRegistration()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "week_number"
     */
    public function testPropertyWeekNumber()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "week_start_date"
     */
    public function testPropertyWeekStartDate()
    {
    }

    /**
     * Test attribute "license_plate"
     */
    public function testPropertyLicensePlate()
    {
    }

    /**
     * Test attribute "mileage"
     */
    public function testPropertyMileage()
    {
    }

    /**
     * Test attribute "driver"
     */
    public function testPropertyDriver()
    {
    }

    /**
     * Test attribute "passenger1"
     */
    public function testPropertyPassenger1()
    {
    }

    /**
     * Test attribute "passenger2"
     */
    public function testPropertyPassenger2()
    {
    }

    /**
     * Test attribute "passenger3"
     */
    public function testPropertyPassenger3()
    {
    }

    /**
     * Test attribute "passenger4"
     */
    public function testPropertyPassenger4()
    {
    }

    /**
     * Test attribute "passenger5"
     */
    public function testPropertyPassenger5()
    {
    }

    /**
     * Test attribute "passenger6"
     */
    public function testPropertyPassenger6()
    {
    }

    /**
     * Test attribute "processed"
     */
    public function testPropertyProcessed()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "updated_by"
     */
    public function testPropertyUpdatedBy()
    {
    }
}
