<?php
/**
 * ProjectSecurityLinkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProjectSecurityLinkTest Class Doc Comment
 *
 * @category    Class
 * @description ProjectSecurityLink
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectSecurityLinkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProjectSecurityLink"
     */
    public function testProjectSecurityLink()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {
    }

    /**
     * Test attribute "cost_type_id"
     */
    public function testPropertyCostTypeId()
    {
    }

    /**
     * Test attribute "security_code_id"
     */
    public function testPropertySecurityCodeId()
    {
    }

    /**
     * Test attribute "budget_amount"
     */
    public function testPropertyBudgetAmount()
    {
    }

    /**
     * Test attribute "prognosis_amount"
     */
    public function testPropertyPrognosisAmount()
    {
    }

    /**
     * Test attribute "prognosis_other_amount"
     */
    public function testPropertyPrognosisOtherAmount()
    {
    }

    /**
     * Test attribute "prognosis_reserved_amount"
     */
    public function testPropertyPrognosisReservedAmount()
    {
    }

    /**
     * Test attribute "additional_work_amount"
     */
    public function testPropertyAdditionalWorkAmount()
    {
    }

    /**
     * Test attribute "progress"
     */
    public function testPropertyProgress()
    {
    }

    /**
     * Test attribute "adjustment"
     */
    public function testPropertyAdjustment()
    {
    }

    /**
     * Test attribute "hour_info"
     */
    public function testPropertyHourInfo()
    {
    }

    /**
     * Test attribute "security_object"
     */
    public function testPropertySecurityObject()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "updated_by"
     */
    public function testPropertyUpdatedBy()
    {
    }
}
