<?php
/**
 * PurchaseOrderContractListItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PurchaseOrderContractListItemTest Class Doc Comment
 *
 * @category    Class
 * @description PurchaseOrderContractListItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PurchaseOrderContractListItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PurchaseOrderContractListItem"
     */
    public function testPurchaseOrderContractListItem()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "supplier"
     */
    public function testPropertySupplier()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "status_name"
     */
    public function testPropertyStatusName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "purchase_type"
     */
    public function testPropertyPurchaseType()
    {
    }

    /**
     * Test attribute "delivery_address"
     */
    public function testPropertyDeliveryAddress()
    {
    }

    /**
     * Test attribute "delivery_date"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "delivery_date_text"
     */
    public function testPropertyDeliveryDateText()
    {
    }

    /**
     * Test attribute "outstanding_costs"
     */
    public function testPropertyOutstandingCosts()
    {
    }

    /**
     * Test attribute "current_approver"
     */
    public function testPropertyCurrentApprover()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "payment_agreement"
     */
    public function testPropertyPaymentAgreement()
    {
    }

    /**
     * Test attribute "linked_delivery_ticket"
     */
    public function testPropertyLinkedDeliveryTicket()
    {
    }

    /**
     * Test attribute "project_security_link"
     */
    public function testPropertyProjectSecurityLink()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "is_email_sent"
     */
    public function testPropertyIsEmailSent()
    {
    }

    /**
     * Test attribute "email_sent_at"
     */
    public function testPropertyEmailSentAt()
    {
    }

    /**
     * Test attribute "email_sent_by"
     */
    public function testPropertyEmailSentBy()
    {
    }

    /**
     * Test attribute "accepted_at"
     */
    public function testPropertyAcceptedAt()
    {
    }

    /**
     * Test attribute "denied_at"
     */
    public function testPropertyDeniedAt()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "attachment_count"
     */
    public function testPropertyAttachmentCount()
    {
    }

    /**
     * Test attribute "called_receipt_count"
     */
    public function testPropertyCalledReceiptCount()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_by"
     */
    public function testPropertyUpdatedBy()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
