<?php
/**
 * PurchaseInvoiceDocumentLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PurchaseInvoiceDocumentLineTest Class Doc Comment
 *
 * @category    Class
 * @description PurchaseInvoiceDocumentLine
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PurchaseInvoiceDocumentLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PurchaseInvoiceDocumentLine"
     */
    public function testPurchaseInvoiceDocumentLine()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unit_name"
     */
    public function testPropertyUnitName()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "gross_price"
     */
    public function testPropertyGrossPrice()
    {
    }

    /**
     * Test attribute "sub_total"
     */
    public function testPropertySubTotal()
    {
    }

    /**
     * Test attribute "vat_tariff_percentage"
     */
    public function testPropertyVatTariffPercentage()
    {
    }

    /**
     * Test attribute "vat_tariff_id"
     */
    public function testPropertyVatTariffId()
    {
    }

    /**
     * Test attribute "ledger"
     */
    public function testPropertyLedger()
    {
    }

    /**
     * Test attribute "cost_center"
     */
    public function testPropertyCostCenter()
    {
    }

    /**
     * Test attribute "delivery_ticket"
     */
    public function testPropertyDeliveryTicket()
    {
    }

    /**
     * Test attribute "model_id"
     */
    public function testPropertyModelId()
    {
    }

    /**
     * Test attribute "model_type"
     */
    public function testPropertyModelType()
    {
    }

    /**
     * Test attribute "create_delivery_ticket_for_remaining_costs"
     */
    public function testPropertyCreateDeliveryTicketForRemainingCosts()
    {
    }

    /**
     * Test attribute "can_be_edited"
     */
    public function testPropertyCanBeEdited()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "updated_by"
     */
    public function testPropertyUpdatedBy()
    {
    }
}
