<?php
/**
 * SurchargeCollectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SurchargeCollectionTest Class Doc Comment
 *
 * @category    Class
 * @description SurchargeCollection
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SurchargeCollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SurchargeCollection"
     */
    public function testSurchargeCollection()
    {
    }

    /**
     * Test attribute "delivery_ticket_percentage"
     */
    public function testPropertyDeliveryTicketPercentage()
    {
    }

    /**
     * Test attribute "work_outsourcing_percentage"
     */
    public function testPropertyWorkOutsourcingPercentage()
    {
    }

    /**
     * Test attribute "purchase_invoice_percentage"
     */
    public function testPropertyPurchaseInvoicePercentage()
    {
    }

    /**
     * Test attribute "material_percentage"
     */
    public function testPropertyMaterialPercentage()
    {
    }

    /**
     * Test attribute "equipment_percentage"
     */
    public function testPropertyEquipmentPercentage()
    {
    }

    /**
     * Test attribute "subcontracting_percentage"
     */
    public function testPropertySubcontractingPercentage()
    {
    }

    /**
     * Test attribute "misc_percentage"
     */
    public function testPropertyMiscPercentage()
    {
    }
}
