<?php
/**
 * ProjectApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bouw7 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProjectApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for canCreateInvoice
     *
     * Returns true if an invoice can be made for the specified project..
     *
     */
    public function testCanCreateInvoice()
    {
    }

    /**
     * Test case for deleteInvoiceTermStatement
     *
     * Delete the given project invoice term statement..
     *
     */
    public function testDeleteInvoiceTermStatement()
    {
    }

    /**
     * Test case for deleteProject
     *
     * Delete the given project..
     *
     */
    public function testDeleteProject()
    {
    }

    /**
     * Test case for getDeletedProjects
     *
     * Returns a list of deleted projects associated with the organization..
     *
     */
    public function testGetDeletedProjects()
    {
    }

    /**
     * Test case for getProject
     *
     * Returns a project associated with the given id..
     *
     */
    public function testGetProject()
    {
    }

    /**
     * Test case for getProjectFile
     *
     * Returns a project file associated with the given id..
     *
     */
    public function testGetProjectFile()
    {
    }

    /**
     * Test case for hardDeleteProject
     *
     * Deletes the given soft deleted project..
     *
     */
    public function testHardDeleteProject()
    {
    }

    /**
     * Test case for listInvoiceTermStatements
     *
     * Returns a list of project invoice term statements associated with the organization..
     *
     */
    public function testListInvoiceTermStatements()
    {
    }

    /**
     * Test case for listInvoiceTerms
     *
     * Returns a list of project invoice terms associated with the organization..
     *
     */
    public function testListInvoiceTerms()
    {
    }

    /**
     * Test case for listProjects
     *
     * Returns a list of projects associated with the organization..
     *
     */
    public function testListProjects()
    {
    }

    /**
     * Test case for postInvoiceTermStatement
     *
     * Create or update the given project invoice term statement..
     *
     */
    public function testPostInvoiceTermStatement()
    {
    }

    /**
     * Test case for postProject
     *
     * Creates or updates the given project..
     *
     */
    public function testPostProject()
    {
    }

    /**
     * Test case for restoreProject
     *
     * Restores the given soft deleted project..
     *
     */
    public function testRestoreProject()
    {
    }

    /**
     * Test case for setInternalNote
     *
     * Sets the internal note of the given project..
     *
     */
    public function testSetInternalNote()
    {
    }
}
